---
*IIT Short Course - Python Programming Lectures*  
*Instructor: Md Mostafizur Rahaman*  
*Email: bsse1320@iit.du.ac.bd*

## Lecture 14: Column Operations With Pandas

Dataset: `person_info.csv`

### Import Libraries

In [1]:
import pandas as pd

### Download Data

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/arman18/data/refs/heads/main/person_info.csv')
df.to_csv('person_info.csv', index=False)

### 1. Data Exploration

Before performing any operations, it's important to explore the dataset to understand its structure, data types, and any potential issues like missing values or incorrect data types.

Let's start by loading the data and exploring it.

In [3]:
# Load the dataset
df = pd.read_csv('person_info.csv')

# Display the first 5 rows to see the data
print("First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:

,ID,Age,Gender,Height,Weight,Income,Education,Employment,Health Condition,Score
0,1,25,M,175,70.0,50000.0,Bachelor,Employed,Good,78.0
1,2,32,F,(160),NaN,60000.0,Master,Unemployed,Excellent,92.0
2,3,45,M,NaN,85.0,75000.0,PhD,Employed,NaN,64.0
3,4,28,F,Tall,500.0,45000.0,Bachelor,Employed,Good,80.0
4,5,38,M,180,95.0,80000.0,High School,Self-employed,Good,72.0

In [4]:
# Get information about the dataset: columns, data types, non-null counts
print("\nDataset information:")
df.info()

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                71 non-null     int64
 1   Age               71 non-null     int64
 2   Gender            70 non-null     str
 3   Height            67 non-null     str
 4   Weight            68 non-null     float64
 5   Income            69 non-null     float64
 6   Education         70 non-null     str
 7   Employment        70 non-null     str
 8   Health Condition  66 non-null     str
 9   Score             70 non-null     float64
dtypes: float64(3), int64(2), str(5)
memory usage: 5.7 KB

In [5]:
# Get summary statistics for numerical columns
print("\nSummary statistics:")
df.describe()

Summary statistics:

              ID        Age      Weight        Income      Score
count  71.000000  71.000000   68.000000     69.000000  70.000000
mean   36.000000  34.873239   78.750000  59289.855072  80.957143
std    20.639767   8.661787   62.415645  21018.970038   8.834117
min     1.000000  21.000000  -15.000000  29000.000000  62.000000
25%    18.500000  28.000000   52.750000  40000.000000  74.000000
50%    36.000000  34.000000   73.500000  60000.000000  78.500000
75%    53.500000  41.000000   88.000000  79000.000000  89.750000
max    71.000000  51.000000  500.000000  93000.000000  95.000000

### 2. Column Subsetting

Column subsetting means selecting specific columns from the DataFrame. This is useful when you only need certain columns for analysis.

You can select columns by name **using square brackets** or the `.loc` accessor.

In [6]:
# Select specific columns by name
selected_columns = df[['ID', 'Age', 'Gender', 'Income']]
print("Selected columns (ID, Age, Gender, Income):")
selected_columns.head()

Selected columns (ID, Age, Gender, Income):

   ID  Age Gender   Income
0   1   25      M  50000.0
1   2   32      F  60000.0
2   3   45      M  75000.0
3   4   28      F  45000.0
4   5   38      M  80000.0

In [7]:
# Select columns using .loc (label-based selection)
# .loc[row_indexer, column_indexer]
height_weight = df.loc[:, ['Height', 'Weight']]
print("\nHeight and Weight columns:")
height_weight.head()

Height and Weight columns:

  Height  Weight
0    175    70.0
1  (160)     NaN
2    NaN    85.0
3   Tall   500.0
4    180    95.0

### 3. DataFrame Filtering

Filtering allows you to select rows that meet certain conditions. This is useful for focusing on specific subsets of data.

Use boolean indexing with comparison operators.

In [8]:
# Filter rows where Age is greater than 30
older_people = df[df['Age'] > 30]
print("People older than 30:")
older_people[['ID', 'Age', 'Gender']].head()

# Filter rows where Gender is 'F' (Female)
females = df[df['Gender'] == 'F']
print("\nFemale participants:")
females[['ID', 'Age', 'Gender', 'Income']].head()

# Combine conditions: Age > 25 AND Income > 50000
young_high_income = df[(df['Age'] > 25) & (df['Income'] > 50000)]
print("\nPeople older than 25 with income > 50000:")
young_high_income[['ID', 'Age', 'Income']].head()

People older than 30:

Female participants:

People older than 25 with income > 50000:

   ID  Age   Income
1   2   32  60000.0
2   3   45  75000.0
4   5   38  80000.0
5   6   38  80000.0
6   7   50  90000.0

### 4. Column Renaming

Sometimes column names need to be changed for clarity or consistency. You can rename columns using the .rename() method.

In [9]:
# Rename specific columns
df_renamed = df.rename(columns={
    'Height': 'height_cm',
    'Weight': 'weight_kg',
    'Income': 'annual_income',
    'Health Condition': 'health_status'
})

print("Columns after renaming:")
print(df_renamed.columns.tolist())

# Display a sample
df_renamed[['ID', 'height_cm', 'weight_kg', 'annual_income']].head()

Columns after renaming:
['ID', 'Age', 'Gender', 'height_cm', 'weight_kg', 'annual_income', 'Education', 'Employment', 'health_status', 'Score']

   ID height_cm  weight_kg  annual_income
0   1       175       70.0        50000.0
1   2     (160)        NaN        60000.0
2   3       NaN       85.0        75000.0
3   4      Tall      500.0        45000.0
4   5       180       95.0        80000.0

### 5. Column Name Standardizing

To make column names consistent, we can convert them to lowercase and replace spaces with underscores. This is a common practice in data analysis.

Use string methods on the columns attribute.

In [10]:
# Standardize column names: convert to lowercase and replace spaces with underscores
cols = df.columns 

# covert the column names to lower case
cols = [col.lower() for col in cols]

# replace spaces with underscores
cols = [col.replace(' ', '_') for col in cols]

df.columns = cols

print("Standardized column names:")
print(df.columns.tolist())

# Display the first few rows with new column names
df.head()

Standardized column names:
['id', 'age', 'gender', 'height', 'weight', 'income', 'education', 'employment', 'health_condition', 'score']

,id,age,gender,height,weight,income,education,employment,health_condition,score
0,1,25,M,175,70.0,50000.0,Bachelor,Employed,Good,78.0
1,2,32,F,(160),NaN,60000.0,Master,Unemployed,Excellent,92.0
2,3,45,M,NaN,85.0,75000.0,PhD,Employed,NaN,64.0
3,4,28,F,Tall,500.0,45000.0,Bachelor,Employed,Good,80.0
4,5,38,M,180,95.0,80000.0,High School,Self-employed,Good,72.0

### 6. Safe Data Type Conversion

Sometimes columns have the wrong data type or contain invalid values. Safe conversion uses `coerce` **to convert invalid values to `NaN` instead of raising errors**.

Use `pd.to_numeric()` for numbers, `pd.to_datetime()` for dates, etc.

In [11]:
# Convert height to numeric (it contains strings like '(160)', 'Tall')
df['height'] = pd.to_numeric(df['height'], errors='coerce')

In [12]:
# Convert weight to numeric (it contains negative values and large numbers)
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')

In [13]:
# Convert income to numeric (should already be, but safe)
df['income'] = pd.to_numeric(df['income'], errors='coerce')

In [14]:
print("Data types after conversion:")
print(df.dtypes)

Data types after conversion:
id                    int64
age                   int64
gender                  str
height              float64
weight              float64
income              float64
education               str
employment              str
health_condition        str
score               float64
dtype: object

In [15]:
# Check for NaN values created by coercion
print("\nNumber of NaN values in each column:")
print(df.isnull().sum())

Number of NaN values in each column:
id                  0
age                 0
gender              1
height              6
weight              3
income              2
education           1
employment          1
health_condition    5
score               1
dtype: int64

### 7. Column Modification

You can modify existing columns or create new ones using mathematical operations or string manipulations.

This includes calculations, transformations, and cleaning categorical data.

In [16]:
# Mathematical calculation: Create BMI column
# BMI = weight (kg) / (height (m))^2
df['bmi'] = df['weight'] / (df['height'] / 100) ** 2

print("Added BMI column:")
df[['id', 'height', 'weight', 'bmi']].head()

Added BMI column:

   id  height  weight        bmi
0   1   175.0    70.0  22.857143
1   2     NaN     NaN        NaN
2   3     NaN    85.0        NaN
3   4     NaN   500.0        NaN
4   5   180.0    95.0  29.320988

In [17]:
# Modify categorical data: Standardize gender values
df['gender'] = df['gender'].str.upper()

# Create age groups
df['age_group'] = pd.cut(df['age'], bins=[0, 25, 35, 50, 100], labels=['Young', 'Adult', 'Middle-aged', 'Senior'])

In [18]:

print("\nAdded age_group column:")
df[['id', 'age', 'gender', 'age_group']].head()

Added age_group column:

   id  age gender    age_group
0   1   25      M        Young
1   2   32      F        Adult
2   3   45      M  Middle-aged
3   4   28      F        Adult
4   5   38      M  Middle-aged

In [19]:
# Clean employment status (capitalize first letter)
df['employment'] = df['employment'].str.capitalize()

print("\nCleaned employment column:")
df[['id', 'employment']].head()

Cleaned employment column:

   id     employment
0   1       Employed
1   2     Unemployed
2   3       Employed
3   4       Employed
4   5  Self-employed

### Practice Questions

#### With Hints
Try these easy exercises to practice what you've learned. Each question includes a slight hint.

1. **How many rows are in the dataset?**  
   *Hint: Use `len(df)` or `df.shape[0]` to get the number of rows.*

2. **What are the unique values in the 'gender' column?**  
   *Hint: Use `df['gender'].unique()` to see distinct values.*

3. **Filter the dataset to show only people with age greater than 40.**  
   *Hint: Use boolean indexing like `df[df['age'] > 40]`.*

4. **Create a new column called 'age_in_months' by multiplying age by 12.**  
   *Hint: Assign to a new column like `df['age_in_months'] = df['age'] * 12`.*

5. **Rename the 'score' column to 'final_score'.**  
   *Hint: Use `df.rename(columns={'score': 'final_score'})`.*

6. **Calculate the average income of all people in the dataset.**  
   *Hint: Use `df['income'].mean()` to get the average.*

7. **Select only the 'id', 'age', and 'income' columns.**  
   *Hint: Use `df[['id', 'age', 'income']]` for subsetting.*

8. **What is the maximum age in the dataset?**  
   *Hint: Use `df['age'].max()` to find the highest value.*

#### Without Hints
Now try similar questions without hints for real practice! (These use different columns or slight variations.)

1. What is the total number of records in the dataset?

2. What are the distinct values in the 'education' column?

3. Show only the rows where the person's income is greater than 50000.

4. Add a new column named 'height_in_inches' that is height multiplied by 0.3937.

5. Change the name of the 'income' column to 'salary'.

6. Find the mean age across all individuals in the data.

7. Extract just the 'id', 'gender', and 'score' columns from the DataFrame.

8. Determine the highest income value present in the dataset.

Try writing the code for each question in a new cell below. You can check your answers by running the cells!